### ISSUE TITLE
[Request] Add strong naming

### ISSUE THREAD

**Issue by SquallATF** [ScarletKuro/Microsoft.Extensions.Hosting.Wpf#10]
If add the .NET Framework support (#9), strong naming assembly need all dependencies  have strong naminged

**Comment by ScarletKuro** [comment]
From what I see, it's has a strong name now https://github.com/ScarletKuro/Microsoft.Extensions.Hosting.Wpf/commit/3498f9df5b3b089a68d463f846074da9ac3d77f4

<img src="https://i.imgur.com/LGc7o6r.png" height="400" />
